apps/adopcion/urls.py
from django.urls import path
from apps.adopcion.views import index_adopcion

app_name = 'adopcion'
urlpatterns = [
    path('index', index_adopcion)
]

apps/mascota/urls.py
from django.urls import path
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
    MascotaList, MascotaCreate

app_name = 'mascota'
urlpatterns = [
    path('', index, name='index'),
    path('nuevo', MascotaCreate.as_view(), name='mascota_crear'),
    # path('nuevo', mascota_view, name='mascota_crear'),
    path('listar', MascotaList.as_view(), name='mascota_listar'),
    # path('listar', mascota_list, name='mascota_listar'),
    path('edit/<mascota_id>/', mascota_edit, name='mascota_editar'),
    path('eliminar/<mascota_id>/', mascota_delete, name='mascota_eliminar'),

]

sitio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls', namespace='mascota')),
    path('adopcion/', include('apps.adopcion.urls', namespace='adopcion')),

]

apps/adopcion/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    domicilio = models.TextField()

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos)

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

# Create your models here.

class Vacuna(models.Model):
    nombre = models.CharField(max_length=40)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad aproximada',
            'fecha_rescate': 'Fecha de rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index_adopcion(request):
    return HttpResponse("Soy la pagina principal de adopcion")

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from django.urls import reverse

from django.http import HttpResponse
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
# Create your views here.

def index(request):
    return render(request, 'mascota/index.html',{})

def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    else:
        form = MascotaForm()
        print(form)
    return render(request, 'mascota/mascota_form.html', {'datos':form, 'edit':False})

def mascota_list(request):
    # mascota = Mascota.objects.all().order_by('id')
    mascota = Mascota.objects.all()
    contexto = {
        'mascota': mascota,
    }
    # print(mascota)
    return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, mascota_id):
    id_mascota = mascota_id
    masco = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=masco)
    else:
        form = MascotaForm(request.POST, instance=masco)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'datos':form, 'edit':True})

def mascota_delete(request, mascota_id):
    id_mascota = mascota_id
    masco = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota':masco})

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascotc.html'
    success_url = 'mascota:mascota_listar'

templates/base/base.html
<!doctype html>

{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- <link rel="icon" href="../../../../favicon.ico"> -->
  <title>Primer DJANGO</title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-primary">
      <div class="container">


        <a class="navbar-brand" href="#">Veterinaria</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mascotas
        </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Registrar</a>
                <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Adopciones
        </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Registrar</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Consultar</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">Cerrar sesión</a>
            </li>
          </ul>
        </div>
        <!-- <a class="navbar-brand" href="#">Fixed top</a> -->
      </div>
    </nav>
  </header>
  <!-- Begin page content -->
  <main role="main" class="container">
    {% block content %} {% endblock %}
    <!-- <h1 class="mt-5">Sticky footer with fixed navbar</h1>
      <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>body &gt; .container</code>.</p>
       -->
  </main>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
  </footer>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
  <!-- <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script> -->
  <!-- <script src="../../assets/js/vendor/popper.min.js"></script> -->
  <!-- <script src="../../dist/js/bootstrap.min.js"></script> -->
</body>

</html>

templates/mascota/index.html
{% extends 'base/base.html'%}

<!-- {% block title %}
  App Mascota
{% endblock %} -->

<!--
{% block header %}
  <h4>Este es el header del index de la app mascota</h4> -->
<!-- {% endblock %} -->

{% block content %}
  <h4>Este es el contenido del index de la app mascota</h4>
{% endblock %}

<!-- {% block footer %}
  <h4>Este es el footer del index de la app mascota</h4>
{% endblock %} -->

templates/mascota/mascota_delete.html
{% extends 'base/base.html '%}

{% block content %}
<form method="POST">
  {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{mascota.nombre}}?</h3>
  <div class="row">
    <div class="col-md-6">
      <button type="submit" name="button" class="btn btn-danger">Si, Eliminar</button>
      <a class="btn btn-default" href="{% url 'mascota:mascota_listar'%}">Cancelar</a>
    </div>
  </div>

</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html '%}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <div class="row">
      <div class="col-md-6">
        <label for="">{{datos.nombre.label_tag}}</label>
        {{datos.nombre}}
      </div>
      <div class="col-md-6">
        <label for="">{{datos.sexo.label_tag}}</label>
        {{datos.sexo}}
      </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-6">
      <label for="">{{datos.edad_aproximada.label_tag}}</label>
      {{datos.edad_aproximada}}
    </div>
    <div class="col-md-6">
      <label for="">{{datos.fecha_rescate.label_tag}}</label>
      {{datos.fecha_rescate}}
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-6">
      <label for="">{{datos.persona.label_tag}}</label>
      {{datos.persona}}
    </div>
    <div class="col-md-6">
      <label for="">{{datos.vacuna.label_tag}}</label>
      {{datos.vacuna}}
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      {% if edit %}
      <button type="submit" name="button" class="btn btn-success">Modificar</button>
      {% else %}
      <button type="submit" name="button" class="btn btn-success">Guardar</button>
      {% endif %}
    </div>
  </div>

</form>
{% endblock %}

<!-- {% for obj in datos %}
  <p>{{obj.label_tag}}</p>
  <p>{{obj}}</p>
{% endfor %} -->

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <td>#</td>
        <td>Nombre</td>
        <td>Sexo</td>
        <td>Edad</td>
        <td>Fecha de rescate</td>
        <td>Adoptante</td>
        <td>Acciones</td>
      </tr>
    </thead>
    <tbody>
      <!--{ mascota } -->
      {% if object_list %}
      {% for mascota in object_list %}
      <tr>
        <td>{{ mascota.id }}</td>
        <td> {{ mascota.nombre}}</td>
        <td> {{ mascota.sexo}}</td>
        <td> {{ mascota.edad_aproximada }}</td>
        <td>{{mascota.fecha_rescate}}</td>
        <td> {{mascota.persona.nombre}} {{mascota.persona.apellidos}}</td>
        <td>
          <a href="{% url 'mascota:mascota_editar' mascota.id%}" class="btn btn-primary">Editar</a>
          <a href="{% url 'mascota:mascota_eliminar' mascota.id%}" class="btn btn-danger">Eliminar</a>
        </td>
      </tr>
      {% endfor%}
      {% else %}
      <h1> No hay registros de mascotas </h1>
      {% endif %}
    </tbody>
    </table>
{% endblock %}

templates/mascota/mascotc.html
{% extends 'base/base.html '%}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" name="button" class="btn btn-success">Guardar</button>
</form>
{% endblock %}